### ISSUE TITLE
no "use this template" button

### ISSUE THREAD

**Issue by michaelaye** [fastai/nbprocess-template#4]
If possible, please also implement the "Use this template" button, like it was there for v1. I found it pretty useful.

**Comment by muellerzr** [comment]
cc @hamelsmu or @jph00 

For right now it takes:

1. `git clone https://github.com/fastai/nbdev-template mylibname`
2. `sudo rm -r .git`
3. `git init`
4. `git add *; git add .github; git add .gitignore` (there may be a better way
5. `git commit -m "Init repo"`
6. Create the new gh repo
7. `git remote add origin URL`
8. `git push origin main -u`

It'd be wonderful to just be able to hit a button and make it 🤗

**Comment by jph00** [comment]
Should be fixed now.

**Comment by jph00** [comment]
FYI @muellerzr you can combine these

> git add *; git add .github; git add .gitignore

    git add * .github .gitignore
